CREATE OR REPLACE NOTIFICATION INTEGRATION snowpipe_event
ENABLED = TRUE
TYPE = QUEUE
NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
AZURE_STORAGE_QUEUE_PRIMARY_URI = 'azure://azuresnowflakestore.queue.core.windows.net/snowflakequeue'
AZURE_TENANT_ID = '3613235f-b2af-499f-9810-ed9841d67046';

DESC INTEGRATION snowpipe_event;

CREATE OR REPLACE PIPE MANAGE_DB.PIPES_SCHEMA.AZURE_PIPE
AUTO_INGEST = TRUE
INTEGRATION = 'SNOWPIPE_EVENT'
AS
COPY INTO OUR_FIRST_DB.PUBLIC.EMPLOYEES
  from @MANAGE_DB.EXTERNAL_STAGES.AZURE_STAGE;