/*Data Masking
    > Column level security
    > Used to mask the sensitive data for security purpose
*/

USE DATABASE DEMO_DB;
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE TABLE CUSTOMERS
(
ID INT,
FULLNAME VARCHAR,
EMAIL VARCHAR,
PHONE VARCHAR,
SPENT NUMBER,
CREATED_DT DATE DEFAULT CURRENT_DATE
);

INSERT INTO CUSTOMERS 
(ID, FULLNAME, EMAIL, PHONE, SPENT)
VALUES
(1,'ARUN','ARUN@GMAIL.COM','980-820-3151',100),
(2,'BALA','BALA@GMAIL.COM','944-258-9739',200),
(3,'CATHY','CATHY@GMAIL.COM','813-105-8998',100),
(4,'DINESH','DINESH@GMAIL.COM','813-047-2750',100),
(5,'ESTHER','ESTHER@GMAIL.COM','515-252-0906',100);

SELECT * FROM CUSTOMERS;

CREATE OR REPLACE ROLE ANALYST_FULL;
CREATE OR REPLACE ROLE ANALYST_MASK;

GRANT USAGE ON DATABASE DEMO_DB TO ROLE ANALYST_FULL;
GRANT USAGE ON DATABASE DEMO_DB TO ROLE ANALYST_MASK;

GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE ANALYST_FULL;
GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE ANALYST_MASK;

GRANT SELECT ON TABLE DEMO_DB.PUBLIC.CUSTOMERS TO ROLE ANALYST_FULL;
GRANT SELECT ON TABLE DEMO_DB.PUBLIC.CUSTOMERS TO ROLE ANALYST_MASK;

GRANT ROLE ANALYST_FULL TO USER TAMIL;
GRANT ROLE ANALYST_MASK TO USER TAMIL;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_FULL;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_MASK;

--CREATE MASKING POLICY
CREATE OR REPLACE MASKING POLICY PHONE AS
(VAL VARCHAR) RETURNS VARCHAR ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','ANALYST_FULL') THEN VAL
    ELSE '###-###-####'
    END;

--ASING MASKING POLICY TO THE TABLE COLUMN
ALTER TABLE CUSTOMERS MODIFY COLUMN PHONE
SET MASKING POLICY PHONE;

SELECT * FROM CUSTOMERS;

USE ROLE ANALYST_FULL;
SELECT * FROM CUSTOMERS;


USE ROLE ANALYST_MASK;
SELECT * FROM CUSTOMERS;

--UNSET AND REPLACE POLICY
/* We can't RECREATE or drop the masking policy until we unset the policy from the table columns*/

DESC MASKING POLICY PHONE;
SHOW MASKING POLICIES;

--Query to check what are all the policies assigned to the table columns
SELECT * FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'PHONE'));

--UNSET THE POLICY
ALTER TABLE CUSTOMERS
MODIFY COLUMN PHONE
UNSET MASKING POLICY;

DROP MASKING POLICY PHONE;

CREATE OR REPLACE MASKING POLICY PHONE AS
(VAL VARCHAR) RETURNS VARCHAR -> --BOTH PARAMETER AND RTURN TYPE SHOULD BE SAME
CASE 
WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','ANALYST_FULL') THEN VAL
ELSE '###-###-####' END;

CREATE OR REPLACE MASKING POLICY NAME AS
(VAL VARCHAR) RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','ANALYST_FULL') THEN VAL
ELSE LEFT(VAL,2) || '*********' END;

ALTER TABLE CUSTOMERS 
MODIFY COLUMN PHONE
SET MASKING POLICY PHONE,
FULLNAME
SET MASKING POLICY NAME;


USE ROLE ANALYST_FULL;
SELECT * FROM CUSTOMERS;


USE ROLE ANALYST_MASK;
SELECT * FROM CUSTOMERS;


--ALTER MASKING POLICY

DESC MASKING POLICY NAME;

ALTER MASKING POLICY NAME SET BODY ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','ANALYST_FULL') THEN VAL
ELSE LEFT(VAL,2) || '#######' END;

USE ROLE ANALYST_MASK;
SELECT * FROM CUSTOMERS;

--REALTIME EXAMPLES
--MASKING EMAIL USING REGEXP
CREATE OR REPLACE MASKING POLICY EMAILS AS
(VAL VARCHAR) RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','ANALYST_FULL') THEN VAL
ELSE REGEXP_REPLACE(VAL,'.+\@','******') END;

ALTER TABLE CUSTOMERS
MODIFY COLUMN EMAIL
SET MASKING POLICY EMAILS;

USE ROLE ANALYST_MASK;
SELECT * FROM CUSTOMERS;

ALTER MASKING POLICY EMAILS SET BODY ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','ANALYST_FULL') THEN VAL
ELSE REGEXP_REPLACE(VAL,'.+\@','******@') END;

USE ROLE ACCOUNTADMIN;

--SHA2
DESC MASKING POLICY NAME;
ALTER MASKING POLICY NAME SET BODY -> 
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','ANALYST_FULL') THEN VAL 
ELSE SHA2(VAL) END; --HASING FUNCTION TO MASK VALUES

USE ROLE ANALYST_MASK;
SELECT * FROM CUSTOMERS;

USE ROLE ACCOUNTADMIN;

--MASKING ROLE FOR CREATED_DT
CREATE OR REPLACE MASKING POLICY DATES AS
(VAL DATE) RETURNS DATE ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','ANALYST_FULL') THEN VAL 
ELSE DATE_FROM_PARTS(0001,01,01)::DATE
END;

ALTER TABLE CUSTOMERS MODIFY COLUMN CREATED_DT
SET MASKING POLICY DATES;

USE ROLE ANALYST_MASK;
SELECT * FROM CUSTOMERS;