USE DATABASE TASK_DB;


CREATE OR REPLACE TASK CUSTOMER_INSERT_CRON
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS
INSERT INTO CUSTOMERS (CREATED_TS) VALUES (CURRENT_TIMESTAMP);



-- --------------------- MINUTE (0-59)
-- | ------------------- HOUR (0-23)
-- | | ----------------- DAY OF MONTH (1-31, OR L)
-- | | | --------------- MONTH (1-12)
-- | | | | ------------- DAY OF WEEK (0-6, SUN-SAT, OR L)
-- | | | | | ----------- TIMEZONE
-- | | | | | |
-- * * * * * UTC 
-- L STANDS TO LAST DAY

//EVERY MINUTE
SCHEDULE = 'USING CRON * * * * * UTC';

//EVERY DAY 6AM UTC
SCHEDULE = 'USING CRON 0 6 * * * UTC';

//EVERY HOUR STARTING FROM 9 AM TO 5 PM ON SUN UTC
SCHEDULE = 'USING CRON 0 9-17 * * SUN UTC';

CREATE OR REPLACE TASK CUSTOMER_INSERT_CRON
WAREHOUSE = COMPUTE_WH
SCHEDULE ='USING CRON 0 9,17 * * 5L UTC' -- SCHEDULE TO RUN ON LAST FRIDAY AT 9 AM AND 5 PM UTC
AS
INSERT INTO CUSTOMERS (CREATED_TS) VALUES (CURRENT_TIMESTAMP);