CREATE OR REPLACE TABLE CUSTOMERS2
(NO INT ,
NAME STRING ,
CREATED_TS TIMESTAMP);

CREATE OR REPLACE TASK CUSTOMER_TASK2
WAREHOUSE = COMPUTE_WH
AFTER  CUSTOMER_TASK
AS
INSERT INTO CUSTOMERS2 SELECT * FROM CUSTOMERS;

CREATE OR REPLACE TABLE CUSTOMERS3
(NO INT ,
NAME STRING ,
CREATED_TS TIMESTAMP,
INSERTED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE OR REPLACE TASK CUSTOMER_TASK3
WAREHOUSE = COMPUTE_WH
AFTER  CUSTOMER_TASK2
AS
INSERT INTO CUSTOMERS3 (NO, NAME, CREATED_TS) SELECT * FROM CUSTOMERS2;

SHOW TASKS;

//RESUME TRESS OF TASK -- START FROM THE CHILD TASK - HERE FROM TASK3 TO TASK

ALTER TASK CUSTOMER_TASK3 RESUME;
ALTER TASK CUSTOMER_TASK2 RESUME;
ALTER TASK CUSTOMER_TASK RESUME;


SELECT * FROM CUSTOMERS;
SELECT * FROM CUSTOMERS2;
SELECT * FROM CUSTOMERS3;

--SUSPEND TASK FROM ROOT
ALTER TASK CUSTOMER_TASK SUSPEND;
ALTER TASK CUSTOMER_TASK2 SUSPEND;
ALTER TASK CUSTOMER_TASK3 SUSPEND;


-- ADD PARENT TASK FOR THE TABLE CREATION
ALTER TASK CUSTOMER_TASK3
ADD AFTER <TASKNAME>;