CREATE WAREHOUSE KAMESH_DEMO_S;

USE WAREHOUSE KAMESH_DEMOS_S;

CREATE DATABASE KAMESH_GIT_REPOS;

USE DATABASE KAMESH_GIT_REPOS;

CREATE SCHEMA GITHUB;

USE SCHEMA GITHUB;

--API INTEGRATION

CREATE OR REPLACE API INTEGRATION KAMESHSAMPATH_GIT
API_PROVIDER = git_https_api
API_ALLOWED_PREFIXES = ('https://github.com/kameshsampath')
enabled = TRUE;

--GIT REPOSITORY
CREATE OR REPLACE GIT REPOSITORY GIT_INTEGRATION_DEMO
API_INTEGRATION = KAMESHSAMPATH_GIT
origin = 'https://github.com/kameshsampath/sf-git-integration-demo.git';

--REFRESH LOCAL REPO
ALTER GIT REPOSITORY GIT_INTEGRATION_DEMO FETCH;

--list the files
LS @GIT_INTEGRATION_DEMO/branches/main;

EXECUTE IMMEDIATE FROM @git_integration_demo/branches/main/demo.sql;