USE ROLE ACCOUNTADMIN;

USE DATABASE DEMO_DB;

USE SCHEMA PUBLIC;

--NO SECRET REQUIRED

--API INTEGRATION
CREATE OR REPLACE API INTEGRATION MY_GIHUB_PUB_INT
API_PROVIDER = GIT_HTTPS_API
API_ALLOWED_PREFIXES = ('https://github.com/Thamizharasan-Gnanaprakasam')
ENABLED = TRUE;

--GIT REPO
CREATE OR REPLACE GIT REPOSITORY MY_GITHUB_PUB_REPO
API_INTEGRATION = MY_GIHUB_PUB_INT
ORIGIN = 'https://github.com/Thamizharasan-Gnanaprakasam/Public_repo';

--SHOW BRANCHES
SHOW GIT BRANCHES IN GIT REPOSITORY MY_GITHUB_PUB_REPO;

--SYNC/FETCH LOCAL REPO

ALTER GIT REPOSITORY MY_GITHUB_PUB_REPO FETCH;

--LS BRANCH
LS @MY_GITHUB_PUB_REPO/branches/main;

--show tags
SHOW GIT TAGS IN GIT REPOSITORY MY_GITHUB_PUB_REPO;

--LIST ALL FILES IN TAG
LS @MY_GITHUB_PUB_REPO/tags/<TAG_ID>;

--LIST ALL FILES BASED ON COMMITS
LS @MY_GITHUB_PUB_REPO/commits/<commit_id>