--CREATE READER ACCOUNT (NON-SF ACCOUNT)

CREATE MANAGED ACCOUNT TECH_JOY_ACCOUNT -- No Replace as managed account can't be replaced
ADMIN_NAME = 'tech_joy',
ADMIN_PASSWORD = 'Tech_joy123',--1 Upper, 1 lower case and 1 digit
TYPE = READER; -- Returns a json content contains accoumt name, account locator and url

--DETAILS OF ACCOUNTS
SHOW MANAGED ACCOUNTS;

--ADD READER ACCOUNT TO THE SHARE
ALTER SHARE ORDERS_SHARE
ADD ACCOUNT = VBB45118; -- IT WILL THORW ERROR IF WE TRY TO SHARE DATA WITH NON BUZ CRITICAL ACCOUNT

-- TO OVERCOME THIS
ALTER SHARE ORDERS_SHARE
ADD ACCOUNT = VBB45118
SHARE_RESTRICTIONS = FALSE;
