CREATE OR REPLACE DATABASE CUSTOMER_DB;

CREATE OR REPLACE FILE FORMAT CUSTOMER_FF
TYPE = CSV,
FIELD_DELIMITER = ',',
SKIP_HEADER = 1,
FIELD_OPTIONALLY_ENCLOSED_BY = '"',
EMPTY_FIELD_AS_NULL = TRUE,
NULL_IF = ('NULL','null');

CREATE OR REPLACE STAGE TIME_TRAVEL_STAGE
URL = 's3://data-snowflake-fundamentals/time-travel/'
FILE_FORMAT = CUSTOMER_FF;

CREATE OR REPLACE TABLE CUSTOMERS(
ID INT,
FIRST_NAME STRING,
LAST_NAME STRING,
EMAIL STRING,
GENDER STRING,
JOB STRING,
PHONE STRING
);


COPY INTO CUSTOMERS
FROM @TIME_TRAVEL_STAGE;

SELECT * FROM CUSTOMERS;

CREATE OR REPLACE VIEW CUSTOMER_VIEW AS -- NORMAL VIEW & CAN'T DO DATA SHARE WITH OTHER ACCOUNTS
SELECT
FIRST_NAME,
LAST_NAME,
EMAIL,
JOB
FROM CUSTOMERS;

GRANT USAGE ON DATABASE CUSTOMER_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA PUBLIC TO ROLE PUBLIC;
GRANT SELECT ON VIEW CUSTOMER_VIEW TO ROLE PUBLIC;


CREATE OR REPLACE SECURE VIEW CUSTOMER_SECURE_VIEW AS -- SECURE VIEW
SELECT
FIRST_NAME,
LAST_NAME,
EMAIL,
JOB
FROM CUSTOMERS;

GRANT USAGE ON DATABASE CUSTOMER_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA PUBLIC TO ROLE PUBLIC;
GRANT SELECT ON VIEW CUSTOMER_SECURE_VIEW TO ROLE PUBLIC;

CREATE OR REPLACE SHARE CUSTOMER_SHARE;

GRANT USAGE ON DATABASE CUSTOMER_DB TO SHARE CUSTOMER_SHARE;
GRANT USAGE ON SCHEMA CUSTOMER_DB.PUBLIC TO SHARE CUSTOMER_SHARE;
GRANT SELECT ON VIEW CUSTOMER_VIEW TO SHARE CUSTOMER_SHARE; -- THIS WILL NOT WORK
GRANT SELECT ON VIEW CUSTOMER_SECURE_VIEW TO SHARE CUSTOMER_SHARE;

ALTER SHARE CUSTOMER_SHARE
ADD ACCOUNT = VBB45118;

--CONSUMER END

CREATE DATABASE CUSTOMER_DB FROM SHARE orb36303.CUSTOMER_SHARE;