CREATE OR REPLACE USER ACCOUNT2
LOGIN_NAME ='ACCOUNT2'
PASSWORD = 'ACCOUNT123'
DEFAULT_WAREHOUSE = XS_WH
DEFAULT_ROLE = SYSADMIN
MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE PUBLIC TO USER ACCOUNT2;

GRANT USAGE ON WAREHOUSE XS_WH TO ROLE PUBLIC;
GRANT IMPORTED PRIVILEGES ON DATABASE DATA_S TO ROLE PUBLIC;