SHOW SHARES;

DESC SHARE orb36303.ORDERS_SHARE;

CREATE OR REPLACE DATABASE DATA_S FROM SHARE orb36303.ORDERS_SHARE;

CREATE OR REPLACE WAREHOUSE XS_WH
WAREHOUSE_SIZE = XSMALL,
WAREHOUSE_TYPE = STANDARD,
AUTO_SUSPEND = 300,
AUTO_RESUME = TRUE,
INITIALLY_SUSPENDED = TRUE;

SELECT * FROM ORDERS;