--DATABASE
CREATE OR REPLACE DATABASE DATA_S;

--STAGE
CREATE OR REPLACE STAGE AWS_STAGE
URL ='s3://bucketsnowflakes3';

--LIST STAGE
list @AWS_STAGE;


--SELECT CONTENT OF STAGE
SELECT $1 FROM @AWS_STAGE;


--TABLE CREATION
CREATE OR REPLACE TABLE ORDERS(
ORDER_ID VARCHAR(30),
AMOUNT NUMBER(38,0),
PROFIT NUMBER(38,0),
QUANTITY NUMBER(38,0),
CATEGORY VARCHAR(30),
SUBCATEGORY VARCHAR(30)
);

--COPY STATEMENT
COPY INTO ORDERS
FROM @AWS_STAGE
FILE_FORMAT = (TYPE = 'CSV', FIELD_DELIMITER = ',', SKIP_HEADER = 1)
PATTERN = '.*Order.*';


--SELECT TABLE
SELECT * FROM ORDERS;

CREATE OR REPLACE STAGE ORDERS_SHARE;

DROP STAGE ORDERS_SHARE;

CREATE OR REPLACE SHARE ORDERS_SHARE;

SHOW SHARES;

--GRNATING PERMISSIONS FOR THE SHARE TO THE OBJECTS
GRANT USAGE ON DATABASE DATA_S TO SHARE ORDERS_SHARE;
GRANT USAGE ON SCHEMA PUBLIC TO SHARE ORDERS_SHARE;
GRANT SELECT ON TABLE ORDERS TO SHARE ORDERS_SHARE;

SHOW GRANTS TO SHARE ORDERS_SHARE;

--ADD CONSUMER ACCOUNT TO THE SHARE
ALTER SHARE ORDERS_SHARE ADD ACCOUNT = ybb57608;