CREATE OR REPLACE SHARE FIRST_DB_SHARE;

GRANT USAGE ON DATABASE OUR_FIRST_DB TO SHARE FIRST_DB_SHARE;
GRANT USAGE ON SCHEMA PUBLIC TO SHARE FIRST_DB_SHARE;

GRANT SELECT ON ALL TABLES IN SCHEMA OUR_FIRST_DB.PUBLIC TO SHARE FIRST_DB_SHARE;

ALTER SHARE FIRST_DB_SHARE
ADD ACCOUNT = VBB45118;


--CONSUMER
SHOW SHARES;

CREATE DATABASE OUR_FIRST_DB FROM SHARE orb36303.FIRST_DB_SHARE;

