--Show Pipe
DESC PIPE MANAGE_DB.PIPES_SCHEMA.S3_PIPE;

SHOW PIPES;

SHOW PIPES LIKE '%PIPE%';

SHOW PIPES IN DATABASE MANAGE_DB;

SHOW PIPES IN SCHEMA MANAGE_DB.PIPES_SCHEMA;

SHOW PIPES LIKE '%PIPE%' IN SCHEMA MANAGE_DB.PIPES_SCHEMA;

--CHECK THE STATE OF PIPE
SELECT SYSTEM$PIPE_STATUS('MANAGE_DB.PIPES_SCHEMA.S3_PIPE');

-- PAUSE PIPE EXECUTION
ALTER PIPE MANAGE_DB.PIPES_SCHEMA.S3_PIPE SET PIPE_EXECUTION_PAUSED = TRUE;

--CHECK THE STATE OF PIPE
SELECT SYSTEM$PIPE_STATUS('MANAGE_DB.PIPES_SCHEMA.S3_PIPE'); -- NEED TO PUT THE PIPE EXECUTION TO PAUSE BEOFRE RECREATING THE PIPE

--CREATE NEW TABLE
CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.EMPLOYEES2 (
ID INT,
FIRST_NAME STRING,
LAST_NAME STRING,
EMAIL STRING,
LOCATION STRING,
DEPARTMENT STRING
);

--FILE FORMAT
ALTER FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FILEFORMAT
SET FIELD_DELIMITER = ',';

CREATE OR REPLACE PIPE MANAGE_DB.PIPES_SCHEMA.S3_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO OUR_FIRST_DB.PUBLIC.EMPLOYEES2
FROM @MANAGE_DB.EXTERNAL_STAGES.S3_STAGE_CSV;

ALTER PIPE MANAGE_DB.PIPES_SCHEMA.S3_PIPE REFRESH; -- SNOWFLAKE WILL MAINTAIN THE METADATA OF PIPE EVEN IF TE PIPE IS RECREATED (NO OLD FILES WILL BE REPROCESSED). WE NEED TO MANUALLY PROCESS IT

ALTER PIPE MANAGE_DB.PIPES_SCHEMA.S3_PIPE SET PIPE_EXECUTION_PAUSED = FALSE;

SELECT SYSTEM$PIPE_STATUS('MANAGE_DB.PIPES_SCHEMA.S3_PIPE');

SELECT * FROM INFORMATION_SCHEMA.LOAD_HISTORY;

SELECT * FROM OUR_FIRST_DB.PUBLIC.EMPLOYEES2;



