CREATE OR REPLACE DATABASE MANAGE_DB;

CREATE OR REPLACE SCHEMA EXTERNAL_STAGES;

//Create a External Stage
CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
URL = 's3://bucketsnowflakes3'
CREDENTIALS=(aws_key_id='ABCD_DUMMY_ID' aws_secret_key='1234abcd_key');

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE;

ALTER STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
SET CREDENTIALS=(aws_key_id='XYZ_DUMMY_ID' aws_secret_key='987xyz');

//PUBLIC AVAILABLE S3 STAGE - SO NO CREDENTIALS REQUIRED

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
url='s3://bucketsnowflakes3';

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE;