CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.MOVIE_TITLES(
SHOW_ID STRING,
TYPE STRING,
TITLE STRING,
DIRECTOR STRING,
CAST STRING,
COUNTRY STRING,
DATE_ADDED STRING,
RELEASE_YEAR STRING,
RATING STRING,
DURATION STRING,
LISTED_ID STRING,
DESCRIPTION STRING
);

//FILE FORMAT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FILEFORMAT
TYPE = CSV,
FIELD_DELIMITER = ',',
SKIP_HEADER = 1,
NULL_IF = ('null','NULL'),
EMPTY_FIELD_AS_NULL = TRUE,
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


//STAGE CREATION
CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.S3_STAGE_CSV
URL = 's3://snowflakes3buckettamil123/csv/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.CSV_FILEFORMAT;

COPY INTO OUR_FIRST_DB.PUBLIC.MOVIE_TITLES
FROM @MANAGE_DB.EXTERNAL_STAGES.S3_STAGE_CSV;