CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.JSON_FILEFORMAT
TYPE = JSON;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.S3_STAGE_JSON
URL = 's3://snowflakes3buckettamil123/json/',
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FILEFORMAT;

SELECT 
$1:asin,
$1:helpful,
$1:overall,
$1:reviewText,
$1:reviewTime,
$1:reviewerID,
$1:reviewerName,
$1:summary,
$1:unixReviewTime
FROM @MANAGE_DB.EXTERNAL_STAGES.S3_STAGE_JSON;

SELECT 
$1:asin::STRING,
$1:helpful,
$1:overall,
$1:reviewText::STRING,
$1:reviewTime::STRING,
$1:reviewerID::STRING,
$1:reviewerName::STRING,
$1:summary::STRING,
DATE($1:unixReviewTime)
FROM @MANAGE_DB.EXTERNAL_STAGES.S3_STAGE_JSON;

SELECT 
$1:asin::STRING,
$1:helpful,
$1:overall,
$1:reviewText::STRING,
TO_DATE($1:reviewTime::STRING,'MM DD, YYYY'), 
/*ALTERNATE WAY - 
DATE_FROM_PARTS(RIGHT($1:reviewTime::STRING, 4),LEFT($1:reviewTime::STRING,2),SUBSTRING(REPLACE($1:reviewTime::STRING,',',''),4,2)),*/
$1:reviewerID::STRING,
$1:reviewerName::STRING,
$1:summary::STRING,
DATE($1:unixReviewTime)
FROM @MANAGE_DB.EXTERNAL_STAGES.S3_STAGE_JSON;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.REVIEWS
(
ASIN STRING,
HELPFUL STRING,
OVERALL INT,
REVIEW_TEXT STRING,
REVIEW_TIME DATE,
REVIEWER_ID STRING,
REVIEWER_NAME STRING,
SUMMARY STRING,
UNIX_REVIEW_TIME DATE
);

COPY INTO OUR_FIRST_DB.PUBLIC.REVIEWS
FROM(SELECT 
$1:asin::STRING,
$1:helpful,
$1:overall,
$1:reviewText::STRING,
TO_DATE($1:reviewTime::STRING,'MM DD, YYYY'), 
/*ALTERNATE WAY - 
DATE_FROM_PARTS(RIGHT($1:reviewTime::STRING, 4),LEFT($1:reviewTime::STRING,2),SUBSTRING(REPLACE($1:reviewTime::STRING,',',''),4,2)),*/
$1:reviewerID::STRING,
$1:reviewerName::STRING,
$1:summary::STRING,
DATE($1:unixReviewTime)
FROM @MANAGE_DB.EXTERNAL_STAGES.S3_STAGE_JSON);

SELECT * FROM OUR_FIRST_DB.PUBLIC.REVIEWS;