--AWS URL: aws.amazon.com

/*
CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STROAGE_AWS_ROLE_ARN = ''
STORAGE_ALLOWED_LOCATIONS = ('<cloud>://<bucket>/<path>/','<cloud>://<bucket>/<path>/')
COMMENT = '<STRING_LITERAL>';
*/

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE,
STORAGE_PROVIDER = S3,
ENABLED = TRUE,
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::420347093111:role/snowflake-access-role', --GET THE ROLE FROM AWS IAM SERVICE -> ROLE -> SELECT THE ROLE -> ARN VALUE FROM THE SUMMARY
STORAGE_ALLOWED_LOCATIONS = ('s3://snowflakes3buckettamil123/csv/','s3://snowflakes3buckettamil123/json/'),
COMMENT = 'THIS IS OUR FIRST STORAGE INTEGRATION';

--DESCRIBE
DESC INTEGRATION S3_INT;

--FROM DESC, GET IAM_USER_ARN AND EXTERNAL_ID AND PASTE IN AWS AND sts:ExternalId keys of the IAM Role json (trust Relationship)