CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS(
ORDERID VARCHAR(30),
AMOUNT INT,
PROFIT INT,
QUANTITY INT,
CATEGORY VARCHAR(30),
SUBCATEGORY VARCHAR(30)
);

SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS;

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE;

//COPY COMMAND
COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
FILE_FORMAT = (TYPE='CSV',
                FIELD_DELIMITER = ','
                SKIP_HEADER = 1); -- WILL FAIL AS ONE OF THE FILE IN STAGE HAS LESS COLUMN COMPARE TO THE COLUMNS IN TABLE

//COPY COMMAND WITH SPECIFIC FILES
COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
FILE_FORMAT = (TYPE='CSV',
                FIELD_DELIMITER = ','
                SKIP_HEADER = 1)
FILES = ('OrderDetails.csv');

//COPY COMMAND WITH FILE PATTERN
COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
FILE_FORMAT = (TYPE='CSV',
                FIELD_DELIMITER = ','
                SKIP_HEADER = 1)
PATTERN = '.*Order.*csv';

SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS;


---Data Transformation

USE DATABASE OUR_FIRST_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE ORDER_EX
(
ORDER_ID VARCHAR(30),
AMOUNT INT
);

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE;

--COPY ONLY SELECTED COLUMNS FROM STAGE FILES

COPY INTO ORDER_EX
FROM (SELECT s.$1, s.$2 FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE s)
FILE_FORMAT = (TYPE='CSV', FIELD_DELIMITER=',', SKIP_HEADER = 1)
FILES = ('OrderDetails.csv');

SELECT * FROM ORDER_EX;

--DERIVED DATA BASED ON THE VALUE IN STAGE FILE AND LOAD INTO TABLE

CREATE OR REPLACE TABLE ORDER_EX
(
ORDER_ID VARCHAR(30),
AMOUNT INT,
PROFIT INT,
PROFITABLE_FLAG VARCHAR(30)
);

COPY INTO ORDER_EX
FROM (SELECT s.$1, s.$2,s.$3,
CASE WHEN CAST(s.$3 AS INT) < 0 THEN 'Not Profitable' ELSE 'Profitable' END 
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE s)
FILE_FORMAT = (TYPE='CSV', FIELD_DELIMITER=',', SKIP_HEADER = 1)
PATTERN = '.*Order.*.csv';

SELECT * FROM ORDER_EX;


--GET SUBSTRING OF A DATA FROM STAGE FILE AND LOAD INTO TABLE

CREATE OR REPLACE TABLE ORDER_EX
(
ORDER_ID VARCHAR(30),
AMOUNT INT,
PROFIT INT,
CATEGORY_SUBSTRING VARCHAR(5)
);

COPY INTO ORDER_EX
FROM (SELECT s.$1, s.$2,s.$3,
SUBSTRING(s.$5,1,5) 
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE s)
FILE_FORMAT = (TYPE='CSV', FIELD_DELIMITER=',', SKIP_HEADER = 1)
PATTERN = '.*Order.*.csv';

SELECT * FROM ORDER_EX;


--COPY SUBSET OF COLUMNS
CREATE OR REPLACE TABLE ORDER_EX
(
ORDER_ID VARCHAR(30),
AMOUNT INT,
PROFIT INT,
PROFITABLE_FLAG VARCHAR(30)
);

COPY INTO ORDER_EX (AMOUNT, PROFIT)
FROM (SELECT s.$2,s.$3
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE s)
FILE_FORMAT = (TYPE='CSV', FIELD_DELIMITER=',', SKIP_HEADER = 1)
PATTERN = '.*Order.*.csv';

SELECT * FROM ORDER_EX;


--COPY SUBSET OF COLUMNS - WITH AUTOINCREMENT IN TABLE
CREATE OR REPLACE TABLE ORDER_EX
(
ORDER_ID INT AUTOINCREMENT START 1 INCREMENT 1,
AMOUNT INT,
PROFIT INT,
PROFITABLE_FLAG VARCHAR(30)
);

COPY INTO ORDER_EX (AMOUNT, PROFIT)
FROM (SELECT s.$2,s.$3
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE s)
FILE_FORMAT = (TYPE='CSV', FIELD_DELIMITER=',', SKIP_HEADER = 1)
PATTERN = '.*Order.*.csv';

SELECT * FROM ORDER_EX;