/*FORCE = TRUE | FALSE
FORCE IS USED TO LOAD THE FILES FORCEFULLY TO THE TABLE EVEN IF THE FILE WAS ALREADY LOADED*/

CREATE OR REPLACE TABLE COPY_DB.PUBLIC.ORDERS (
ORDER_ID VARCHAR(30),
AMOUNT VARCHAR(30),
PROFIT INT,
QUANTITY INT,
CATEGORY VARCHAR(30),
SUBCATEGORY VARCHAR(30)
);


COPY INTO ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE_COPY
FILE_FORMAT = (TYPE = CSV, FIELD_DELIMITER = ',', SKIP_HEADER = 1)
PATTERN = '.*Order.*';  -- THIS WILL LOAD

COPY INTO ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE_COPY
FILE_FORMAT = (TYPE = CSV, FIELD_DELIMITER = ',', SKIP_HEADER = 1)
PATTERN = '.*Order.*';  -- THIS WILL LOAD NO DATA

COPY INTO ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE_COPY
FILE_FORMAT = (TYPE = CSV, FIELD_DELIMITER = ',', SKIP_HEADER = 1)
PATTERN = '.*Order.*'
FORCE = TRUE; -- THIS WILL LOAD