/*RETURN_FAILED_ONLY = TRUE | FALSE
This option is set to true if we need to return the files which are failed to load
*/

CREATE OR REPLACE TABLE COPY_DB.PUBLIC.ORDERS (
ORDER_ID VARCHAR(30),
AMOUNT VARCHAR(30),
PROFIT INT,
QUANTITY INT,
CATEGORY VARCHAR(30),
SUBCATEGORY VARCHAR(30)
);

CREATE OR REPLACE STAGE COPY_DB.PUBLIC.AWS_STAGE_COPY
URL = 's3://snowflakebucket-copyoption/returnfailed/';

COPY INTO ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE_COPY
FILE_FORMAT = (TYPE = CSV, FIELD_DELIMITER = ',', SKIP_HEADER = 1)
PATTERN = '.*Order.*'
RETURN_FAILED_ONLY = TRUE; -- THIS WILL NOT WORK, THIS WILL WORK ALONG WITH ON_ERROR OPTION

COPY INTO ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE_COPY
FILE_FORMAT = (TYPE = CSV, FIELD_DELIMITER = ',', SKIP_HEADER = 1)
PATTERN = '.*Order.*'
ON_ERROR = CONTINUE
RETURN_FAILED_ONLY = TRUE; -- THIS WILL  WORK