/*LOAD HISTORY WILL HELP US TO RETERIVE THE HISTORY OF DATA LOADED TO THE TABLE USING COPY INTO STATEMENT*/

-- THIS WILL GIVE THE INFORMATION ONLY AFTER THE TABLE IS RECREATED
SELECT * FROM COPY_DB.INFORMATION_SCHEMA.LOAD_HISTORY;

--BELOW IS USED TO GET THE GLOBAL INFO OF LOAD HISTORY

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY;

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY
WHERE LAST_LOAD_TIME <= DATEADD('DAYS',1, CURRENT_DATE);