CREATE OR REPLACE TABLE COPY_DB.PUBLIC.ORDERS (
ORDER_ID VARCHAR(30),
AMOUNT VARCHAR(30),
PROFIT INT,
QUANTITY INT,
CATEGORY VARCHAR(30),
SUBCATEGORY VARCHAR(30)
);

/*ONE WAY*/

COPY INTO COPY_DB.PUBLIC.ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE_COPY
PATTERN = '.*Order.*'
FILE_FORMAT = (TYPE = CSV, FIELD_DELIMITER = ',', SKIP_HEADER = 1)
VALIDATION_MODE = RETURN_ERRORS; -- This will not load any data to table and also no rewos will be returned as all the records a valid


SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

CREATE OR REPLACE TABLE REJECTED_RECORDS AS
SELECT REJECTED_RECORD FROM TABLE(RESULT_SCAN('01af18f2-0604-bdef-0000-0000ff5b460d'));

SELECT * FROM REJECTED_RECORDS;

DESC TABLE REJECTED_RECORDS;

/*ALTERNATE WAY*/

COPY INTO COPY_DB.PUBLIC.ORDERS
FROM @COPY_DB.PUBLIC.AWS_STAGE_COPY
PATTERN = '.*Order.*'
FILE_FORMAT = (TYPE = CSV, FIELD_DELIMITER = ',', SKIP_HEADER = 1)
ON_ERROR = CONTINUE; -- This will not load any data to table and also no rewos will be returned as all the records a valid


SELECT * FROM TABLE(VALIDATE(ORDERS, JOB_ID => '_last'));

SELECT
SPLIT_PART(REJECTED_RECORD,',',1) AS ORDER_ID,
SPLIT_PART(REJECTED_RECORD,',',2) AS AMOUNT,
SPLIT_PART(REJECTED_RECORD,',',3) AS PROFIT,
SPLIT_PART(REJECTED_RECORD,',',4) AS QUANTITY,
SPLIT_PART(REJECTED_RECORD,',',5) AS CATEGORY,
SPLIT_PART(REJECTED_RECORD,',',6) AS SUBCATEGORY
FROM REJECTED_RECORDS;
