CREATE OR REPLACE FILE FORMAT FILE_FORMATS.PARQUET_FORMAT
TYPE = PARQUET;

CREATE OR REPLACE STAGE EXTERNAL_STAGES.PARQUET_STAGE
URL = 's3://snowflakeparquetdemo'
FILE_FORMAT = (FORMAT_NAME = FILE_FORMATS.PARQUET_FORMAT);

LS @EXTERNAL_STAGES.PARQUET_STAGE;

SELECT * FROM @EXTERNAL_STAGES.PARQUET_STAGE;

CREATE OR REPLACE STAGE EXTERNAL_STAGES.PARQUET_STAGE
URL = 's3://snowflakeparquetdemo';

LS @EXTERNAL_STAGES.PARQUET_STAGE;

SELECT * FROM @EXTERNAL_STAGES.PARQUET_STAGE; -- THIS WILL NOT WORK

SELECT * FROM @EXTERNAL_STAGES.PARQUET_STAGE
(FILE_FORMAT => FILE_FORMATS.PARQUET_FORMAT); -- THIS WILL WORK

SELECT * FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
(FILE_FORMAT => MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT); -- THIS WILL ASO WORK

{
  "__index_level_0__": 7,
  "cat_id": "HOBBIES",
  "d": 489,
  "date": 1338422400000000,
  "dept_id": "HOBBIES_1",
  "id": "HOBBIES_1_008_CA_1_evaluation",
  "item_id": "HOBBIES_1_008",
  "state_id": "CA",
  "store_id": "CA_1",
  "value": 12
};

SELECT
$1:__index_level_0__ AS INDEX_LEVEL,
$1:cat_id AS CATEGORY_ID,
$1:date as DATE,
$1:dept_id as DEPARTMENT_ID,
$1:id as ID,
$1:item_id as ITEM_ID,
$1:state_id as STATE_ID,
$1:store_id as STORE_ID,
$1:value as VALUE
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
(FILE_FORMAT => MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT);


SELECT
$1:__index_level_0__::INT AS INDEX_LEVEL,
$1:cat_id::VARCHAR(50) AS CATEGORY_ID,
DATE($1:date::INT) as DATE,
$1:dept_id::VARCHAR(50) as DEPARTMENT_ID,
$1:id::VARCHAR(50) as ID,
$1:item_id::VARCHAR(50) as ITEM_ID,
$1:state_id::VARCHAR(50) as STATE_ID,
$1:store_id::VARCHAR(50) as STORE_ID,
$1:value::INT as VALUE
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
(FILE_FORMAT => MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT);


SELECT
$1:__index_level_0__::INT AS INDEX_LEVEL,
$1:cat_id::VARCHAR(50) AS CATEGORY_ID,
DATE($1:date::INT) as DATE,
$1:dept_id::VARCHAR(50) as DEPARTMENT_ID,
$1:id::VARCHAR(50) as ID,
$1:item_id::VARCHAR(50) as ITEM_ID,
$1:state_id::VARCHAR(50) as STATE_ID,
$1:store_id::VARCHAR(50) as STORE_ID,
$1:value::INT as VALUE,
METADATA$FILENAME,
METADATA$FILE_ROW_NUMBER,
CURRENT_TIMESTAMP::TIMESTAMP_NTZ
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
(FILE_FORMAT => MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT);

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.PARQUET_DATA
(
ROW_NUMBER INT,
INDEX_LEVEL INT,
CATEGORY_ID VARCHAR(50),
DATE DATE,
DEPARTMENT_ID VARCHAR(50),
ID VARCHAR(50),
ITEM_ID VARCHAR(50),
STATE_ID VARCHAR(50),
STORE_ID VARCHAR(50),
VALUE VARCHAR(50),
LOAD_DATE TIMESTAMP
);

COPY INTO OUR_FIRST_DB.PUBLIC.PARQUET_DATA
FROM (SELECT
METADATA$FILE_ROW_NUMBER,
$1:__index_level_0__::INT AS INDEX_LEVEL,
$1:cat_id::VARCHAR(50) AS CATEGORY_ID,
DATE($1:date::INT) as DATE,
$1:dept_id::VARCHAR(50) as DEPARTMENT_ID,
$1:id::VARCHAR(50) as ID,
$1:item_id::VARCHAR(50) as ITEM_ID,
$1:state_id::VARCHAR(50) as STATE_ID,
$1:store_id::VARCHAR(50) as STORE_ID,
$1:value::INT as VALUE,
CURRENT_TIMESTAMP::TIMESTAMP_NTZ
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE)
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT
FORCE = TRUE;



SELECT
$1:__index_level_0__::INT AS INDEX_LEVEL,
$1:cat_id::VARCHAR(50) AS CATEGORY_ID,
DATE($1:date::INT) as DATE,
$1:dept_id::VARCHAR(50) as DEPARTMENT_ID,
$1:id::VARCHAR(50) as ID,
$1:item_id::VARCHAR(50) as ITEM_ID,
$1:state_id::VARCHAR(50) as STATE_ID,
$1:store_id::VARCHAR(50) as STORE_ID,
$1:value::INT as VALUE,
METADATA$FILENAME,
METADATA$FILE_ROW_NUMBER,
CURRENT_TIMESTAMP::TIMESTAMP_NTZ
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT; -- THIS WILL NOT WORK