CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.JSONSTAGE
URL = 's3://bucketsnowflake-jsondemo/';

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.JSONFORMAT
TYPE = JSON;

ls @MANAGE_DB.EXTERNAL_STAGES.JSONSTAGE;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.JSON_RAW
(
RAW_FILE VARIANT
);

COPY INTO OUR_FIRST_DB.PUBLIC.JSON_RAW
FROM @MANAGE_DB.EXTERNAL_STAGES.JSONSTAGE
FILE_FORMAT = (FORMAT_NAME = MANAGE_DB.FILE_FORMATS.JSONFORMAT)
FILES = ('HR_data.json');

SELECT * FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:first_name FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT $1:first_name FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:first_name::VARCHAR AS FIRST_NAME FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:id::INTEGER AS ID FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:id::INTEGER AS ID,
RAW_FILE:first_name::STRING AS FIRST_NAME,
RAW_FILE:last_name::STRING AS LAST_NAME,
RAW_FILE:gender::STRING AS GENDER
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:job
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;



SELECT RAW_FILE:job.salary::NUMBER AS SALARY,
RAW_FILE:job.title::STRING AS TITLE
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:id::INTEGER AS ID,
RAW_FILE:first_name::STRING AS FIRST_NAME,
RAW_FILE:last_name::STRING AS LAST_NAME,
RAW_FILE:gender::STRING AS GENDER,
RAW_FILE:job.salary::NUMBER AS SALARY,
RAW_FILE:job.title::STRING AS TITLE
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT
RAW_FILE:prev_company
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT ARRAY_SIZE(RAW_FILE:prev_company)
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT
RAW_FILE:prev_company[0]
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT
RAW_FILE:prev_company[1]
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:spoken_languages
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:spoken_languages[0]
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:spoken_languages[0].language::string,
RAW_FILE:spoken_languages[0].level::string
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT RAW_FILE:id::INT AS ID,
RAW_FILE:first_name::STRING AS FIRST_NAME,
RAW_FILE:last_name::STRING AS LAST_NAME,
f.value:language::string as language,
f.value:level::string as level
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW, TABLE(FLATTEN(RAW_FILE:spoken_languages)) f;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.LANGUAGES AS
SELECT RAW_FILE:id::INT AS ID,
RAW_FILE:first_name::STRING AS FIRST_NAME,
RAW_FILE:last_name::STRING AS LAST_NAME,
f.value:language::string as language,
f.value:level::string as level
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW, TABLE(FLATTEN(RAW_FILE:spoken_languages)) f;

SELECT * FROM OUR_FIRST_DB.PUBLIC.LANGUAGES;

TRUNCATE OUR_FIRST_DB.PUBLIC.LANGUAGES;

INSERT INTO OUR_FIRST_DB.PUBLIC.LANGUAGES 
SELECT RAW_FILE:id::INT AS ID,
RAW_FILE:first_name::STRING AS FIRST_NAME,
RAW_FILE:last_name::STRING AS LAST_NAME,
f.value:language::string as language,
f.value:level::string as level
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW, TABLE(FLATTEN(RAW_FILE:spoken_languages)) f;

SELECT * FROM OUR_FIRST_DB.PUBLIC.LANGUAGES;