/*
SYNTAX:
SELECT ...
FROM ...
  { SAMPLE | TABLESAMPLE } [ samplingMethod ] ( { <probability> | <num> ROWS } ) [ { REPEATABLE | SEED } ( <seed> ) ]

samplingMethod: ROW OR BLOCK
ROW - FOR SMALLER TABLE
BLOCK - FOR LARGE TABLE

probability - GET THE DATA FROM TABLE WITH PROBABLITY OF (p/100)*n - Value Ranges  from 0 to 100
num - TO GET EXACT NUMBER OF ROWS. RANGES FROM 0 TO 1000000

SEED IS USED TO RETURN SAME RESULT FOR N NUMBER OF EXECUTION OF SAME QUERY
*/


SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS;


--ROW METHOD
CREATE OR REPLACE VIEW CUSTOMER_ADDRESS_VIEW AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS
SAMPLE ROW (1) SEED (27);

SELECT COUNT(1) FROM CUSTOMER_ADDRESS_VIEW; --324,576

SELECT COUNT(1) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS; --32,500,000

--BLOCK METHOD
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS
SAMPLE BLOCK (1) SEED (27);