/* Access Control - Who can access and perform operations on the objects in SF

2 types of access control that are combined in it

1. Discretionary Access Control (DAC) - Each object has an owner who can grant access to it

2. Role-Based Access Control (RBAC) - Access privelege assined to role and in turn, role is assigned to the users

Securable Objects
                        ACCOUNT
                            |
                            V
Users    Role    Database    Warehouse    Other_Account_objects
                    |
                    V
                Schemas
                    |
                    V
Tables    Functions    Stages    File Formats    Views    Integration    Other Schema Objects

*/

--ACCOUNTADMIN - CAN DO ALL THESE TASK

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE TEST1;

CREATE OR REPLACE ROLE ROLE_ADMIN;

GRANT USAGE ON DATABASE TEST1 TO ROLE ROLE_ADMIN;
GRANT USAGE ON SCHEMA TEST1.PUBLIC TO ROLE ROLE_ADMIN;

CREATE OR REPLACE USER USER_ADMIN;

GRANT ROLE ROLE_ADMIN TO USER USER_ADMIN;

GRANT ROLE ROLE_ADMIN TO ROLE SECURITYADMIN;
GRANT ROLE ROLE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE ROLE_ADMIN TO ROLE USERADMIN;
GRANT ROLE ROLE_ADMIN TO ROLE ACCOUNTADMIN;

CREATE MANAGED ACCOUNT READER_ACCT1
ADMIN_NAME ='ADMIN'
ADMIN_PASSWORWD = 'Admin123'
TYPE = READER;

SHOW MANAGED ACCOUNTS;

--SECURITYADMIN - No Object creatin under security group

USE ROLE securityadmin;
use warehouse compute_wh;

CREATE OR REPLACE DATABASE TEST2; --NOT POSSIBLE

CREATE OR REPLACE ROLE ROLE_SEC;

GRANT USAGE ON DATABASE TEST1 TO ROLE ROLE_SEC;
GRANT USAGE ON SCHEMA TEST1.PUBLIC TO ROLE ROLE_SEC;

CREATE OR REPLACE USER USER_SEC PASSWORD = '123' MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ROLE_SEC TO USER USER_SEC;

GRANT ROLE ROLE_SEC TO ROLE SECURITYADMIN;
GRANT ROLE ROLE_SEC TO ROLE SYSADMIN;
GRANT ROLE ROLE_SEC TO ROLE USERADMIN;
GRANT ROLE ROLE_SEC TO ROLE ACCOUNTADMIN;



SHOW ROLES;


--SYSADMIN - No user/role Cretion

USE ROLE SYSADMIN;
use warehouse compute_wh;

CREATE OR REPLACE DATABASE TEST3;

CREATE OR REPLACE ROLE ROLE_SYS; -- NOT POSIBLE

GRANT USAGE ON DATABASE TEST3 TO ROLE ROLE_SEC;
GRANT USAGE ON SCHEMA TEST3.PUBLIC TO ROLE ROLE_SEC;

CREATE OR REPLACE USER USER_SYS PASSWORD = '123' MUST_CHANGE_PASSWORD = TRUE; -- NOT POSSIBLE

GRANT ROLE ROLE_SEC TO USER USER_SEC;

GRANT ROLE ROLE_SEC TO ROLE SECURITYADMIN;
GRANT ROLE ROLE_SEC TO ROLE SYSADMIN;
GRANT ROLE ROLE_SEC TO ROLE USERADMIN;
GRANT ROLE ROLE_SEC TO ROLE ACCOUNTADMIN;

SHOW ROLES;

--USERADMIN - Only user/role Cretion and assing the roles (oiwned by USERADMIN) to the users

USE ROLE USERADMIN;
use warehouse compute_wh;

CREATE OR REPLACE DATABASE TEST4; -- NOT POSSIBLE

CREATE OR REPLACE ROLE ROLE_USER;

GRANT USAGE ON DATABASE TEST2 TO ROLE ROLE_USER;
GRANT USAGE ON SCHEMA TEST2.PUBLIC TO ROLE ROLE_USER;

CREATE OR REPLACE USER USER_SYS PASSWORD = '123' MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ROLE_USER TO USER USER_SYS;

GRANT ROLE ROLE_SEC TO ROLE SECURITYADMIN;
GRANT ROLE ROLE_SEC TO ROLE SYSADMIN;
GRANT ROLE ROLE_SEC TO ROLE USERADMIN;
GRANT ROLE ROLE_SEC TO ROLE ACCOUNTADMIN;

SHOW ROLES;