USE DATABASE EXERCISE_DB;
USE SCHEMA PUBLIC;

DESC TABLE CUSTOMERS;

CREATE OR REPLACE STAGE CUST_STAGE
URL = 's3://snowflake-assignments-mc/loadingdata/'
FILE_FORMAT = (TYPE='CSV', FIELD_DELIMITER=';', SKIP_HEADER=1);

DESC STAGE CUST_STAGE;

LIST @CUST_STAGE;

//COPY STATEMENT - TYPE 1
COPY INTO CUSTOMERS
FROM @CUST_STAGE;

SELECT COUNT(1) FROM CUSTOMERS; --2600

//COPY STATEMENT - TYPE 2 - SPECIFY FILEFORMT
COPY INTO CUSTOMERS
FROM @CUST_STAGE
FILE_FORMAT = (TYPE='CSV', FIELD_DELIMITER = ';', SKIP_HEADER=1);

SELECT COUNT(1) FROM CUSTOMERS; --2600

//COPY STATEMENT - TYPE 3 - SPECY FILE NAME
COPY INTO CUSTOMERS
FROM @CUST_STAGE
FILES = ('customers2.csv','customers3.csv');

SELECT COUNT(1) FROM CUSTOMERS; --2600

//COPY STATEMENT - TYPE 4 FILE PATTERN
COPY INTO CUSTOMERS
FROM @CUST_STAGE
PATTERN = '.*customers.*csv';

SELECT COUNT(1) FROM CUSTOMERS; --2600
