SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;

SELECT 
DATABASE_NAME,
COUNT(1) NO_OF_QUERIES,
SUM(CREDITS_USED_CLOUD_SERVICES)
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
GROUP BY 1;

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY;

SELECT
DATE(START_TIME),
SUM(CREDITS_USED)
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY 1;

SELECT
WAREHOUSE_NAME,
SUM(CREDITS_USED)
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY 1;

SELECT
WAREHOUSE_NAME,
DATE(START_TIME),
SUM(CREDITS_USED)
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY 1,2
ORDER BY 1,2;

SHOW PARAMETERS;