SHOW ORGANIZATION ACCOUNTS;

SELECT SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER('<ORGANIZATION_NAME>.<ACCOUNT_NAME>','ENABLE_ACCOUNT_DATABASE_REPLICATION','TRUE');

ALTER DATABASE MY_DB1 ENABLE REPLCATION TO ACCOUNTS MYORG.ACCOUNT2,MYORG.ACCOUNT3;

--CONSUMER END

CREATE DATABASE MY_DB1 AS REPLICA OF MYORG.ACCOUNT1.MY_DB1;

SHOW TABLES IN SCHEMA SECOND_SCHEMA;

GRANT USAGE ON DATABASE CUSTOMER_DB TO ROLE ANALYST_FULL;
GRANT USAGE ON SCHEMA CUSTOMER_DB.PULIC TO ROLE ANALYST_FULL;

CREATE OR REPLACE TABLE CUSTOMER_DB.PUBLIC.EMPLOYEES_ASSIGN61
CLONE EMPLOYEES_ASSIGN6;

ALTER DATABASE MY_DB1 REFRESH; --OWNERSHIP PRIVILEGES REQUIRED TO REFRESH