-- can use from Standard edition
-- Use CIDR notation

Allowed IP Addresses: 192.168.1.0/24 -- range 192.168.1.0 - 192.168.1.255
Blocked IP addresses: 192.168.1.75, 192.168.1.15  -- Has priority

--Security Admin OR GLOBAL CREATE NETWORKPOLICY PRIVILEGE
CREATE NETWORK POLICY MY_NETWORK_POLICY
ALLOWED_IP_LIST = (IP ADDRESSES)
BLOCKED_IP_LIST = (IP ADDRESSES);

--SET TO ACOUNT
ALTER ACCOUNT SET NETWORK_POLICY = MY_NETWORK_POLICY;
ALTER ACCOUNT UNSET NETWORK_POLICY

ALTER USER SET NETWORK_POLICY = MY_NETWORK_POLICY;