SELECT AVG(C_BIRTH_YEAR)
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER; -- run twice 


CREATE OR REPLACE ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_SCIENTIST;

SHOW USERS;

GRANT ROLE DATA_SCIENTIST TO USER DS1;