--This is for Complex queries

DESC WAREHOUSE COMPUTE_WH;
SHOW WAREHOUSES LIKE '%COMPUTE_WH%';

ALTER WAREHOUSE COMPUTE_WH
SET WAREHOUSE_SIZE = SMALL; -- SCALE UP - FROM XS TO S

ALTER WAREHOUSE COMPUTE_WH
SET WAREHOUSE_SIZE = XSMALL; -- SCALE DOWN - FROM S TO XS