CREATE OR REPLACE TABLE SAMPLE_TBL
(
NO NUMBER,
NAME VARCHAR
)
CHANGE_TRACKING = TRUE;

ALTER TABLE SAMPLE_TBL
SET CHANGE_TRACKING = TRUE;

SELECT * FROM SAMPLE_TBL
CHANGES(INFORMATION => DEFAULT)
AT (OFFSET => -120);

SELECT * FROM SAMPLE_TBL
CHANGES(INFORMATION => APPEND_ONLY)
AT (OFFSET => -120);

INSERT INTO SAMPLE_TBL
VALUES
(2,'ARUN');

UPDATE SAMPLE_TBL SET NAME = 'BALA'
WHERE NO=2;