CREATE OR REPLACE DATABASE STREAMS_DB;

CREATE OR REPLACE TABLE SALES_RAW_STAGING(
ID VARCHAR,
PRODUCT VARCHAR,
PRICE VARCHAR,
AMOUNT VARCHAR,
STORE_ID VARCHAR
);

INSERT INTO SALES_RAW_STAGING VALUES
(1, 'Banana',1.99,1,1),
(2,'Lemon','0.99',1,1),
(3,'Apple',1.79,1,2),
(4,'Orange Juice',1.89,1,2),
(5,'Cereals','5.98',2,1);

CREATE OR REPLACE TABLE STORE_TABLE(
STORE_ID NUMBER,
LOCATION VARCHAR,
EMPLOYEES NUMBER
);

INSERT INTO STORE_TABLE VALUES (
1, 'Chicago',33
),
(2,'London',12);

CREATE OR REPLACE TABLE SALES_FINAL_TABLE(
ID INT,
PRODUCT VARCHAR,
PRICE NUMBER,
AMOUNT INT,
STORE_ID INT,
LOCATION VARCHAR,
EMPLOYEES INT
);

INSERT INTO SALES_FINAL_TABLE
SELECT 
SR.ID,
SR.PRODUCT,
SR.PRICE,
SR.AMOUNT,
SR.STORE_ID,
ST.LOCATION,
ST.EMPLOYEES
FROM SALES_RAW_STAGING SR
JOIN STORE_TABLE ST
ON SR.STORE_ID = ST.STORE_ID;

--CREATE STREAM
CREATE OR REPLACE STREAM SALES_STREAM ON TABLE SALES_RAW_STAGING;

INSERT INTO SALES_RAW_STAGING VALUES
(6,'Mango',1.99,2,1),
(7,'Garlic',0.99,1,2);

SELECT * FROM SALES_RAW_STAGING; --7 ROWS

SELECT * FROM SALES_STREAM; -- 2 ROWS

--INSERT

INSERT INTO SALES_FINAL_TABLE
SELECT 
SR.ID,
SR.PRODUCT,
SR.PRICE,
SR.AMOUNT,
SR.STORE_ID,
ST.LOCATION,
ST.EMPLOYEES
FROM SALES_STREAM SR
JOIN STORE_TABLE ST
ON SR.STORE_ID = ST.STORE_ID; -- INSERTED 2 ROWS

--UPDATE
UPDATE SALES_RAW_STAGING SET PRODUCT='Papaya'
WHERE PRODUCT = 'Banana';

SELECT * FROM SALES_RAW_STAGING; -- BANANA UPDATED TO PAPAYA

SELECT * FROM SALES_STREAM; -- WILL SEE 2 RECORDS FOR AN UPDATE, ONE WITH ACTION DELETE AND OTHER WITH INSERT. FOR BOTH ISUPDATE WILL BE TRUE

--QUERY TO INSERT THE UPDATED RECORD USING STREAM

MERGE INTO SALES_FINAL_TABLE A
USING SALES_STREAM B
ON A.ID = B.ID
WHEN MATCHED
AND METADATA$ACTION = 'INSERT'
AND METADATA$ISUPDATE = TRUE
THEN UPDATE
SET A.ID = B.ID,
A.PRODUCT = B.PRODUCT,
A.PRICE = B.PRICE,
A.AMOUNT = B.AMOUNT,
A.STORE_ID=B.STORE_ID;

SELECT * FROM SALES_FINAL_TABLE;

--DELETE

SELECT * FROM SALES_RAW_STAGING;

DELETE FROM SALES_RAW_STAGING WHERE PRODUCT = 'Lemon';

SELECT * FROM SALES_STREAM; -- 1 ROW WITH ACTION AS DELETE AND ISUPDATE IS FALSE

--MERGING THE DELETE TO FINAL TABLE

MERGE INTO SALES_FINAL_TABLE A
USING SALES_STREAM B
ON A.ID = B.ID
WHEN MATCHED
AND B.METADATA$ACTION = 'DELETE'
AND B.METADATA$ISUPDATE = FALSE
THEN DELETE;

SELECT * FROM SALES_FINAL_TABLE;
