CREATE OR REPLACE STREAM SALES_STREAM_DEFAULT
ON TABLE SALES_RAW_STAGING; --STANDARD OR DEFAULT STREAM AND WILL TRACK ALL 3 DML OPERATIONS

CREATE OR REPLACE STREAM SALES_STREAM_APPEND
ON TABLE SALES_RAW_STAGING
APPEND_ONLY = TRUE; --APPEND ONLY STREAM AND WILL TRACK ONLY INSERT OPERATION


SHOW STREAMS;
