CREATE OR REPLACE STORAGE INTEGRATION GCP_INT
TYPE = EXTERNAL_STAGE,
STORAGE_PROVIDER = GCS
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = ('gcs://snowflakegcp-bucket-json','gcs://snowflakegcp-bucket');

DESC INTEGRATION GCP_INT; -- ADD SCP SERVICE ACCOUNT TO BUCKET -> SELECT THE BUCKET NAME, CLICK ON PERMISSIONS -> ADD PRINCIPAL -> PASTE THE ACCOUNT IN "ADD PRINCIPAL FIELD" AND SELECT ROLE AS " CLOUD STORAGE -> STORAGE ADMIN"