--CSV
SELECT
$1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
$11, $12, $13, $14, $15, $16, $17, $18, $19, $20
FROM @MANAGE_DB.EXTERNAL_STAGES.GCP_STAGE_CSV;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.HAPPINESS
(
COUNTRY_NAME VARCHAR,
REGIONAL_INDICATOR VARCHAR,
LADDED_SCORE NUMBER(4,3),
STD_ERR_LADDER_SCORE NUMBER(4,3),
UPPER_WHISKER NUMBER(4,3),
LOWER_WHISKER NUMBER(4,3),
LOGGED_GDP_NO NUMBER(5,3),
SOCIAL_SUPPORT NUMBER(4,3),
HEALTH_LIFE NUMBER(5,3),
FREEDOM_CHOICE NUMBER(4,3),
GENEROSITY NUMBER(4,3),
PERCEP_CORR NUMBER(4,3),
LADDER_SCORE_DYSTOPIA NUMBER(4,3),
EXPLAIN_LOG_GDP NUMBER(4,3),
EXPLAIN_SOCIAL_SUPPORT NUMBER(4,3),
EXPLAIN_HEALTH_LIFE NUMBER(4,3),
EXPLAIN_FREEDOM_CHOICE NUMBER(4,3),
EXPLAIN_GENEROSITY NUMBER(4,3),
EXPLAIN_PERCEP_CORR NUMBER(4,3),
DYSTOPIA_RESIDUAL NUMBER(4,3)
);

COPY INTO OUR_FIRST_DB.PUBLIC.HAPPINESS
FROM @MANAGE_DB.EXTERNAL_STAGES.GCP_STAGE_CSV;

--JSON
select $1 from @MANAGE_DB.EXTERNAL_STAGES.GCP_STAGE_JSON;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.CAR_MODEL_JSON
(RAW VARIANT);

COPY INTO OUR_FIRST_DB.PUBLIC.CAR_MODEL_JSON
FROM @MANAGE_DB.EXTERNAL_STAGES.GCP_STAGE_JSON;