CREATE OR REPLACE TRANSIENT DATABASE TDB;

CREATE OR REPLACE TRANSIENT SCHEMA TRANS_SCHEMA;

SHOW SCHEMAS;

CREATE OR REPLACE TABLE TEST
(NO NUMBER,
NAME VARCHAR);

SHOW TABLES;

CREATE OR REPLACE TEMPORARY TABLE TEST(NO NUMBER);