CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.AZURE_FILEFORMAT_CSV
TYPE = CSV,
FIELD_DELIMITER = ',',
SKIP_HEADER = 1,
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL','null')
EMPTY_FIELD_AS_NULL = TRUE;


CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AZURE_STAGE
URL = 'azure://azuresnowflakestore.blob.core.windows.net/snowflakecsv',
STORAGE_INTEGRATION = AZURE_INT,
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.AZURE_FILEFORMAT_CSV;

LS @MANAGE_DB.EXTERNAL_STAGES.AZURE_STAGE;