/*Syntax
STEP 1:
CREATE OR REPLACE STORAGE INTEGRATION AZURE_INT
TYPE = EXTERNAL_STAGE
ENABLED = TRUE
STORAGE_PROVIDER = AZURE
STORAGE_ALLOWED_LOCATIONS = ('azure://storage-account.blob.core.windows.net/container/path/data')
AZURE_TENANT_ID = '<your-azure-tenant-id>';

STEP 2:
DESC INTEGRATION 
    AND NAVIGATE TO THE URL GIVEN IN AZURE_CONSENT_URL AND CHECK CONSENT ON BEHALF OF YOUR ORGANIZATION

STEP 3:
NAVIGATE TO STORAGE ACCOUNT -> ACCESS CONTROL (IAM) AND ADD NEW ROLE ASSIGNMENT
    SELECT "Storage Blob Data Contributor" UNDER "JOB FUNCTION ROLES"

*/

CREATE OR REPLACE STORAGE INTEGRATION AZURE_INT
TYPE = EXTERNAL_STAGE
ENABLED = TRUE
STORAGE_PROVIDER = AZURE
STORAGE_ALLOWED_LOCATIONS = ('azure://azuresnowflakestore.blob.core.windows.net/snowflakejson','azure://azuresnowflakestore.blob.core.windows.net/snowflakecsv')
AZURE_TENANT_ID = '91d04424-afba-4671-a3df-652c645aa90e'; -- GET IT FROM Azure Active Directory (if Tenant ID is not available, create one)

DESC INTEGRATION AZURE_INT; -- NAVIGATE TO THE URL GIVEN IN AZURE_CONSENT_URL AND CHECK CONSENT ON BEHALF OF YOUR ORGANIZATION



