SHOW TABLES LIKE '%EMP%';

ALTER TABLE OUR_FIRST_DB.PUBLIC.EMPLOYEES1
SET DATA_RETENTION_TIME_IN_DAYS = 2;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.TEST_TBL
(NO NUMBER,
NAME VARCHAR)
DATA_RETENTION_TIME_IN_DAYS = 3;

SHOW TABLES LIKE '%TEST_TBL%';

