USE DATABASE MANAGE_DB;
USE SCHEMA EXTERNAL_STAGES;

CREATE OR REPLACE STAGE ASSIGN_4
URL = 's3://snowflake-assignments-mc/fileformat/';

CREATE OR REPLACE FILE FORMAT FILE_FORMATS.MY_ASSIGN4_FORMAT
TYPE = CSV,
FIELD_DELIMITER = '|'
SKIP_HEADER = 1;

LIST @ASSIGN_4;

TRUNCATE EXERCISE_DB.PUBLIC.CUSTOMERS;

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
FROM @ASSIGN_4
FILE_FORMAT = (FORMAT_NAME = FILE_FORMATS.MY_ASSIGN4_FORMAT);

SELECT COUNT(1) FROM EXERCISE_DB.PUBLIC.CUSTOMERS;