CREATE OR REPLACE TABLE EMPLOYEES_ASSIGN6
(
customer_id int,
first_name varchar(50),
last_name varchar(50),
email varchar(50),
age int,
department varchar(50)
);

CREATE OR REPLACE STAGE AWS_STAGE_ASSING6
URL = 's3://snowflake-assignments-mc/copyoptions/example2';

LS @AWS_STAGE_ASSING6;

CREATE OR REPLACE FILE FORMAT ASSING6_FF
TYPE = CSV,
FIELD_DELIMITER = ',',
SKIP_HEADER = 1;

COPY INTO EMPLOYEES_ASSIGN6
FROM @AWS_STAGE_ASSING6
FILE_FORMAT = (FORMAT_NAME = ASSING6_FF)
VALIDATION_MODE = RETURN_ERRORS;

COPY INTO EMPLOYEES_ASSIGN6
FROM @AWS_STAGE_ASSING6
FILE_FORMAT = (FORMAT_NAME = ASSING6_FF)
TRUNCATECOLUMNS = TRUE;

SELECT COUNT(1) FROM EMPLOYEES_ASSIGN6; --62