--CREATE SHARE
CREATE OR REPLACE SHARE CUSTOMER_SHARE;

GRANT USAGE ON DATABASE CUSTOMER_DB TO SHARE CUSTOMER_SHARE;
GRANT USAGE ON SCHEMA CUSTOMER_DB.PUBLIC TO SHARE CUSTOMER_SHARE;
GRANT SELECT ON TABLE CUSTOMER_DB.PUBLIC.CUSTOMERS TO SHARE CUSTOMER_SHARE;

--ADDING SF ACCOUNT
ALTER SHARE CUSTOMER_SHARE
ADD ACCOUNT = sdw135733;

--ADD CONSUMER END: sdw135733
CREATE OR REPLACE DATABASE CUSTOMER_DB FROM SHARE asd163257.CUSTOMER_SHARE;

--CREATE READER_ACCOUNT
CREATE MANAGED ACCOUNT READER_ACCOUNT
ADMIN_NAME = 'READER_ADMIN',
ADMIN_PASSWORD = 'Admin123',
TYPE = READER;

SHOW MANAGED ACCOUNTS;

--ADD READER ACCOUNT TO THE SHARE
ALTER SHARE CUSTOMER_SHARE
ADD ACCOUNT = IWB85712
SHARE_RESTRICTIONS = FALSE;

--CREATE DB FROM SHARE
CREATE OR REPLACE DATABASE CUSTOMER_DB FROM SHARE asd163257.CUSTOMER_SHARE;

