USE ROLE ACCOUNTDMIN;
USE DATABASE DEMO_DB;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.PART
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."PART";

SELECT * FROM PART
ORDER BY P_MFGR DESC;

UPDATE DEMO_DB.PUBLIC.PART
SET P_MFGR='Manufacturer#CompanyX'
WHERE P_MFGR='Manufacturer#5'; --01af2963-0604-bf7d-0000-ff5b0001128a

SELECT * FROM PART
ORDER BY P_MFGR DESC;

SELECT * FROM PART BEFORE (OFFSET => -60*3)
ORDER BY P_MFGR DESC;

SELECT * FROM PART BEFORE (STATEMENT => '01af2963-0604-bf7d-0000-ff5b0001128a')
ORDER BY P_MFGR DESC;