USE DATABASE DEMO_DB;

SELECT 
AVG(PS_SUPPLYCOST) as PS_SUPPLYCOST_AVG,
AVG(PS_AVAILQTY) as PS_AVAILQTY_AVG,
MAX(PS_COMMENT) as PS_COMMENT_MAX
FROM"SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."PARTSUPP"; -- 01af40e5-0604-bf7b-0000-ff5b00016b02; 8.4s

CREATE OR REPLACE SECURE MATERIALIZED VIEW PARTS AS
SELECT 
AVG(PS_SUPPLYCOST) as PS_SUPPLYCOST_AVG,
AVG(PS_AVAILQTY) as PS_AVAILQTY_AVG,
MAX(PS_COMMENT) as PS_COMMENT_MAX
FROM"SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."PARTSUPP"; --8.1s

SELECT * FROM PARTS; --575ms

GRANT SELECT ON VIEW PARTS TO ROLE PUBLIC;
GRANT USAGE ON DATABASE DEMO_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE PUBLIC;

SHOW VIEWS IN DATABASE DEMO_DB;