USE DATABASE EXERCISE_DB;

SELECT * FROM MANAGE_DB.PUBLIC.JSON_RAW;

SELECT RAW:first_name::STRING AS FIRST_NAME,
RAW:last_name::STRING AS LAST_NAME,
RAW:Skills
FROM MANAGE_DB.PUBLIC.JSON_RAW;

CREATE OR REPLACE TABLE EMPLOYEE_ASSIGN8 AS
SELECT RAW:first_name::STRING AS FIRST_NAME,
RAW:last_name::STRING AS LAST_NAME,
RAW:Skills[0]::STRING AS SKILL_1,
RAW:Skills[1]::STRING AS SKILL_2
FROM MANAGE_DB.PUBLIC.JSON_RAW;

SELECT * FROM EMPLOYEE_ASSIGN8 WHERE FIRST_NAME = 'Florina';

SELECT RAW:first_name::STRING AS FIRST_NAME,
RAW:last_name::STRING AS LAST_NAME,
RAW:Skills
FROM MANAGE_DB.PUBLIC.JSON_RAW
WHERE RAW:first_name::STRING = 'Florina'; --[   "Hatha Yoga" ]